image: node:14

definitions:
  caches:
    frontend-modules: node_modules
  steps:
    - step: &build
        name: Build
        caches:
          - frontend-modules
        script:
          - yarn install --production=false --non-interactive --no-progress --frozen-lockfile
          - yarn build
        artifacts:
          - dist/**

pipelines:
  pull-requests:
    '**':
      - step: &build
  branches:
    develop-test:
      - step: *build
          #image: node:14
      #    name: Build frontend
      #    caches:
      #      - node
      #    script:
      #      - yarn install --production=false --non-interactive --no-progress --frozen-lockfile --cwd source/frontend
      #      - yarn --cwd source/frontend build
      #    artifacts:
      #      - source/frontend/build/**
      #- step:
      #    name: Deploy to Monkapps
      #    script:
      #      - pipe: atlassian/rsync-deploy:0.4.4
      #        variables:
      #          USER: 'uala-website-development'
      #          SERVER: 'us.dev.monkapps.com'
      #          LOCAL_PATH: 'source/frontend/build/build/'
      #          EXTRA_ARGS: '-avPx'
      #          REMOTE_PATH: '~/public/'
