image: node:14

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install and Build
          caches:
            - node
          script:
            - yarn
            - yarn check-types
            - yarn lint 
  branches:
    develop-test:
      - step:
          name: Build frontend
          caches:
            - node
          script:
            - yarn install --production=false --non-interactive --no-progress --frozen-lockfile
            - yarn build
          artifacts:
            - build/**
      #- step:
      #    name: Deploy to Monkapps
      #    script:
      #      - pipe: atlassian/rsync-deploy:0.4.4
      #        variables:
      #          USER: 'uala-website-development'
      #          SERVER: 'us.dev.monkapps.com'
      #          LOCAL_PATH: 'source/frontend/build/build/'
      #          EXTRA_ARGS: '-avPx'
      #          REMOTE_PATH: '~/public/'
