import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import BlockWrapper from '../components/BlockWrapper/BlockWrapper';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ualá - Media.Monks Website Development</h1>

        <div className={styles.grid}>
          <Link href="/LandingPage-AR">
            <a className={styles.card}>
              <h2>Argentina</h2>
              <p>View Landing Page for Argentina region.</p>
            </a>
          </Link>
          <Link href="/LandingPage-CO">
            <a className={styles.card}>
              <h2>Colombia</h2>
              <p>View Landing Page for Colombia region.</p>
            </a>
          </Link>
          <Link href="/LandingPage-MX">
            <a className={styles.card}>
              <h2>México</h2>
              <p>View Landing Page for México region.</p>
            </a>
          </Link>
        </div>
        <BlockWrapper customClass={[styles.howTo]}>
          <h2 className={styles.description}>How to integrate:</h2>
          <p>This Repository contains all the components to fulfill the tree regions.</p>
          <p>
            Find the page for each region and copy the content into the{' '}
            <span className={styles.code}>index.js</span> of each region repository
          </p>
          <p>
            The data is being handled in a <span className={styles.code}>.json</span> file located
            in <span className={styles.code}>/data/Site[region]Content.json</span>. All content
            should be edited there.
          </p>
        </BlockWrapper>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
